name: Commit Validations

on:
  pull_request:
    branches:
      - main

jobs:
  commit_lint:
    name: Run Commit Lint
    uses: zcode-ia/gitops-workflows/.github/workflows/commit-lint.yml@35061a1947682fb5c33841d94a9d14886ef5743e # v1.14.1
