name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    uses: zcode-ia/gitops-workflows/.github/workflows/release.yml@main
    with:
      owner: ${{ github.repository_owner }}
      repositories: 'gitops-platform-catalog'
    secrets:
      github_app_id: ${{ secrets.CREATE_TOKEN_APP_ID }}
      github_app_private_key: ${{ secrets.CREATE_TOKEN_APP_PRIVATE_KEY }}
