name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    uses: zcode-ia/gitops-workflows/.github/workflows/release.yml@main
    secrets:
      github_secret_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
